### ISSUE TITLE
How to do the same but with Hapi?

### ISSUE THREAD

**Issue by tttony** [murtuzaalisurti/express-to-vercel#1]
Hi! (commenting here since in you site can't comment)

I tested this sample app and I have played with it, adding routes, etc.. and it works, in fact it was the only one that worked from all samples I gathered on the web

I have a project but I did it with Hapi (just a hobby project) and I was wondering if it is possible to setup my Hapi project in Vercel, I know you can config Vercel to work with Hapi but using Next.js (https://github.com/vercel/next.js/tree/canary/examples/custom-server-hapi) but maybe it's there a way to set it up like Express?

Thanks!

**Comment by murtuzaalisurti** [comment]
This might be helpful https://hapi.dev/tutorials/expresstohapi/?lang=en_US
Just export the hapi app using `module.exports` like we do in express `module.exports = app` where `app = require('express')();`

**Comment by tttony** [comment]
Cool thanks! 

After a long test I just noticed that your **vercel.json** does not have the **version**, I just removed and it worked with Hapi, I was using a version.json from another project that didn't work, I guess that was the problem
